version: "3.0"

services:
  dev:
    image: blog
    command: ["bundle", "exec", "jekyll", "serve", "--no-watch", "--force_polling", "--incremental", "--livereload"]
    ports:
      - "4000:4000"
    volumes:
      - ${PROJ_DIR}:/srv/jekyll